### ISSUE TITLE
the patching dont work after 7.31

### ISSUE THREAD

**Issue by ryouik1** [Wolf49406/Dota2Patcher#10]
after coming in game and trying to select hero there is a issue that says to many threads... and smth else.
Hope u will fix it soon^_^

**Comment by Wolf49406** [comment]
And how do you think patching couple of bytes will affect threads?
It's not related to patcher and can't be.

**Comment by Wolf49406** [comment]
This one? It's not about patcher, this is normal dota behavior.

![image](https://user-images.githubusercontent.com/26302888/155430951-1f00dfa3-2d63-4ceb-b052-5e9fa145cabe.png)

**Comment by ryouik1** [comment]
This window appears after i want to select any hero except primal beast. Dota crashing. This happend after i patched gameinfo to use nobling mod.
![Screenshot_1](https://user-images.githubusercontent.com/97785848/155431951-75caa0dc-782d-4b9e-98f2-f695fe04c762.png)

**Comment by Wolf49406** [comment]
Try to rebuild NoBling. It's not about patcher.

**Comment by ryouik1** [comment]
yes, i fixed this problem by deleting -threads launch options. But now nobling is not working.  I use it again but it has no effect. Im feeling that dota don run pak01_dir.vpk from dota_tempcontent. Idk what's wrong, bcs im added -tempcontent launc option...

**Comment by Wolf49406** [comment]
-tempcontent [was completely removed](https://github.com/SteamDatabase/GameTracking-Dota2/commit/e793776d4038bc76f48779af9bf009db19d64247#diff-b14ae59d5038832206b3236b4a2e19936a4b0e6cc3402a59e326cf4a249a24cd).
You need to [read some ReadMe](https://github.com/Wolf49406/Dota2Patcher#how-to-1) and edit gameinfo.gi.
