### ISSUE TITLE
not working after new update

### ISSUE THREAD

**Issue by zorelix** [Wolf49406/Dota2Patcher#12]
some plugins arent working after update like see tp on fog etc update please thank you

**Comment by Wolf49406** [comment]
Did you patch AGAIN after dota 2 update? You should try.

**Comment by zorelix** [comment]
i did no luck :(

**Comment by Wolf49406** [comment]
Everything works for me ¯(°_o)/¯

**Comment by elventevil** [comment]
@zorelix its working bro, revert patch than try to patch again, and u have to copy paste console before every single game

**Comment by zorelix** [comment]
it is working now. thank you guys hehehe :D
