### ISSUE TITLE
Perpetual "Update required" cycle

### ISSUE THREAD

**Issue by ZzZombo** [Wolf49406/Dota2Patcher#13]
Your program has a bug. I have the latest release, but it still forces me to update it because the hardcoded "current version" value is set to an old version, 3.0.4.2, so the comparison is always true, and so it will always demand to update.

On a related note, I don't think forcing the user to update is appropriate. It may suggest to, but please leave the choice to me, thanks!

**Comment by Wolf49406** [comment]
Well, just download a latest version 🤔
But yes, i'll remove force update later. Or do something to self-update app.

**Comment by ZzZombo** [comment]
But I did! The application even open exactly the same release page of your repo! Look, your `Globals` points to an old version, like I said above, so the update check always succeeds because the comparison will never find the two compared strings equal.

**Comment by Wolf49406** [comment]
But it's 3.0.4.5 everywhere 🤔
https://github.com/Wolf49406/Dota2Patcher/blob/master/Dota2Patcher.h#L23
https://raw.githubusercontent.com/Wolf49406/Dota2Patcher/master/version.txt
Also i have never met this problem, everything's ok for me.

**Comment by ZzZombo** [comment]
So are you saying if you download the latest release from the Releases page, you do not have to update when running the application?

**Comment by Wolf49406** [comment]
Exactly.

**Comment by Wolf49406** [comment]
So... is it somehow got fixed?

**Comment by ZzZombo** [comment]
No! I've redownloaded the binary and it still insist on getting updated first.

**Comment by Wolf49406** [comment]
That's weird. Everyone who use it facing no problem.
You can open [this page](https://raw.githubusercontent.com/Wolf49406/Dota2Patcher/master/version.txt), right?
Isn't it blocked by your firewall or something? It looks like updater just can't get right data from link above.

**Comment by Wolf49406** [comment]
Try again.
https://github.com/Wolf49406/Dota2Patcher/releases/tag/V3.0.4.6
![image](https://user-images.githubusercontent.com/26302888/160425043-253d8ada-f33e-4479-aaa4-c1b4e89aef5a.png)

**Comment by ZzZombo** [comment]
> Update required!
> Local version: 3.0.4.6
> Remote version:
> Download latest release here:
> https://github.com/Wolf49406/Dota2Patcher/releases/latest
> Or press any key to continue

Thank you, appreciated! I just realized why it happens: my system uses a global MitM-proxy for HTTP(S) traffic, your linked curl copy isn't configured to use the `schannel` backend apparently, thus it doesn't trust the self-signed certificate generated by the proxy, aborting the connection before it may download anything at all.

**Comment by Wolf49406** [comment]
I guess CURLOPT_SSL_VERIFYPEER set to 0 should help. Can you check it?
[Dota2Patcher.zip](https://github.com/Wolf49406/Dota2Patcher/files/8376830/Dota2Patcher.zip)

**Comment by ZzZombo** [comment]
Yep, it worked!

**Comment by Wolf49406** [comment]
[a7df7ac](https://github.com/Wolf49406/Dota2Patcher/commit/a7df7ac4eb1fc698fcfadff88c20923be98434ae)
