### ISSUE TITLE
I purchased your new release of cheat software Crimson. So many features don't work.

### ISSUE THREAD

**Issue by IkaMusumeGitHub** [Wolf49406/Dota2Patcher#14]
I purchased your new release of cheat software Crimson.
So many features don't work.
1. Enter "-PerfectWorld" in "Dota launch options" and start the game, it will crash and close after the game starts.
2. "Visible By Enemy [PRO]" does not work
3. "MapHack [PRO]" does not work
I have purchased the premium version for 500 rubles.

**Comment by Wolf49406** [comment]
Did you disable Free-Version Toggle in launcher menu?
Did you enter your key?
Did you enable this functions in cheat menu (in-game)?
Also, you don't need to use -PerfectWorld. It does nothing AFAIK. Just use regular gameinfo method.

**Comment by IkaMusumeGitHub** [comment]
I entered the KEY.
The free version is not enabled.
I started dota2 through Crimson.
I purchased it through a friend.

**Comment by Wolf49406** [comment]
Check in-game menu (press Delete).
![image](https://user-images.githubusercontent.com/26302888/164199083-1a4134ad-c51b-4143-9cca-76e7078aa804.png)

**Comment by IkaMusumeGitHub** [comment]
This one I turned on.
Another thing is that when I start Crimson, sometimes this pops up. Not sure what this is.
![1](https://user-images.githubusercontent.com/99901574/164199698-2c827162-5ffb-4b63-9231-20fc7efe2501.png)

**Comment by Wolf49406** [comment]
It's an update :D

**Comment by IkaMusumeGitHub** [comment]
![2](https://user-images.githubusercontent.com/99901574/164200051-91856441-f557-42a1-aa2c-92cd5f599923.png)
Still no work.
Is it because of my game's language setting? Or, is it a windows language problem?

**Comment by Wolf49406** [comment]
I guess it's because of Demo Mode. Try regular lobby.

**Comment by IkaMusumeGitHub** [comment]
Hahahaha, it worked :)

**Comment by IkaMusumeGitHub** [comment]
Thank you.

**Comment by Wolf49406** [comment]
Enjoy, and thanks for buying <3
