### ISSUE TITLE
CRC Check bypass not working

### ISSUE THREAD

**Issue by mediv0** [Wolf49406/Dota2Patcher#15]
instruction inside READM is not working.
Getting VAC Modified File Error

**Comment by tofuboitofu** [comment]
true

**Comment by Wolf49406** [comment]
Oh, i got it. Did toy update bypass after latest path? Toldja!
![image](https://user-images.githubusercontent.com/26302888/165990470-60e233d1-d2a9-4917-9a85-05a142f30bc3.png)

**Comment by mediv0** [comment]
> Oh, i got it. Did you update bypass after latest path? Tolja! ![image](https://user-images.githubusercontent.com/26302888/165990470-60e233d1-d2a9-4917-9a85-05a142f30bc3.png)

i dont think so 
gonna try it later 
thank you <3
