### ISSUE TITLE
[-] Registry Read Failed at RegOpenKey, Error: 1

### ISSUE THREAD

**Issue by iPurya** [Wolf49406/Dota2Patcher#18]
Hi
i ran it as administartor but still get this error
![image](https://user-images.githubusercontent.com/58905883/166163233-32f05689-3347-4ed5-a0cb-e84dccb3eb08.png)

**Comment by Wolf49406** [comment]
Did you just install dota and never run it?

**Comment by iPurya** [comment]
i just reinstalled.
