### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by Lgazana** [Wolf49406/Dota2Patcher#2]
Hello, this is some cool software you've got here ;D!
I just wanted to ask if the file "engine2.dll" is the only one being patched, and if not, could you write me a list of all the files being patched so that I can save them in a Zip archive before using your "Dota2Patcher" and just extract and replace later, because the "Verifying Integrity of Game Files" process takes about 10 minutes on my computer and I want to avoid it if possible. Also, how safe am I from getting vac banend if I use this?

**Comment by Wolf49406** [comment]
Nah, it's just one byte patch in engine.dll. I'll probably add "revert everything back" feature later.
[https://github.com/Wolf49406/Dota2Patcher/blob/ac7716a216198ae39a2d72622e83f0b071eff2e2/Patcher.cs#L91](url)

**Comment by Lgazana** [comment]
Ohh That would be fantastic ;P and thank you for your response!

**Comment by Wolf49406** [comment]
> Also, how safe am I from getting vac banend if I use this?
Ah yes. This is 100% safe, VAC never checks dlls.
Otherwise, launching Dota would take as much time as checking the integrity of the game files.

**Comment by Lgazana** [comment]
Oh, lol, I assumed you didn't want to answer that part, so I didn't want to bother you any further, but thank you for clarifying; now I can play and relax xD.
