### ISSUE TITLE
Your Patcher Is Being Detected As Trojan

### ISSUE THREAD

**Issue by thunderstone135** [Wolf49406/Dota2Patcher#20]
Hi, I just want to let you know that the latest version of your patcher is being detected as trojan.

![Imgur](https://imgur.com/wb3NU7f.png)

Of course, I checked your code and I don't see anything malicious in it.
In fact, it's just v3.0.4.9 that is being tagged as a trojan.
It seems to me that Steam is taking an interest in your work.

**Comment by Wolf49406** [comment]
O_O

**Comment by Wolf49406** [comment]
Guess i'm gonna use some VMProtect to mutate exe... later.
