### ISSUE TITLE
Expection Unhandled

### ISSUE THREAD

**Issue by 0xb4dc0d3x** [Wolf49406/Dota2Patcher#21]
Hi I cloned your project and when I compiled and executed it I got this error:

Unhandled exception at 0x00007FFC618E474C in Dota2Patcher.exe: Microsoft C++ exception: std::bad_array_new_length at memory location 0x000000152F2FFA00.

I tried all patch functions
- Patch all
- Unlock Dota Plus 
- Patch sv_cheats

**Comment by 0xb4dc0d3x** [comment]
Your release works but when I compile it, It give that error

**Comment by Wolf49406** [comment]
Idk man, really. Try to debug and you'll see where is the problem.

**Comment by 0xb4dc0d3x** [comment]
It's my fault and I commented this if condition
I'm so sorry
https://github.com/Wolf49406/Dota2Patcher/blob/f967abc1690a121face09cc72c9a1ca2f0814825/Dota2Patcher.cpp#L54

**Comment by Wolf49406** [comment]
It's ok <3
