### ISSUE TITLE
DotA 2 Patcher doesn't work anymore

### ISSUE THREAD

**Issue by YaphzOr** [Wolf49406/Dota2Patcher#23]
It says the same thing that it said during installation of dota 2 mods. VAC prevents matchmaking due to modified files.

**Comment by YaphzOr** [comment]
Either that or the valve figured out how to disable this mod by deleting the game info file itself. Because after editing gameinfo.gi is the reason why I could run this mod in the first place.

**Comment by Wolf49406** [comment]
Dude... 
![image](https://user-images.githubusercontent.com/26302888/181433624-89346fdd-90f3-4e3b-9e2d-84c2156c2c53.png)
![image](https://user-images.githubusercontent.com/26302888/181434054-1856981d-5af1-412b-a1a3-9dcaa5e4526a.png)

**Comment by YaphzOr** [comment]
My bad, somehow gameinfo file and 3 other files git deleted that's why it was showing me vac warning.

**Comment by Wolf49406** [comment]
I guess it's ok, dota has few quite big updates nova days.
