### ISSUE TITLE
requesting a Silent mode feature

### ISSUE THREAD

**Issue by MaimedThoughts** [Wolf49406/Dota2Patcher#24]
Hello @Wolf49406! Thank you for updating this fantastic app! I discovered that I could update the No-Bling vpk silently by adding '-s' to the end of the command 'vpkmod.exe -b -s' and began to wonder if I could do the same with Dota2Patcher.exe and update both of them without touching the keyboard at all. So my question is, can you add a small feature to Dota2Patcher.exe to allow it to accept command line like this?
start "" "D:\Dota2Patcher.exe" -1 to patch everything silently
start "" "D:\Dota2Patcher.exe" -5 to silently revert patches

**Comment by Wolf49406** [comment]
Hey, that's actually pretty good. Take a look at https://github.com/Wolf49406/Dota2Patcher/blob/5da00078d8193b8cded295690692055407f84f5f/Dota2Patcher.cpp#L71
So now you can do something like `Dota2Patcher.exe -2 -3` to `Unlock Dota Plus` and `Patch sv_cheats`.
Also you can use `-s` as FIRST argument (ex: `Dota2Patcher.exe -s -2 -3`) and everything will be silently (No output or "Press any key" at all).
Just create a shortcut and add your params. Or even a .bat with command to start dota automatically after patching.

**Comment by MaimedThoughts** [comment]
@Wolf49406 Yep that's exactly what I was looking for. Thank you so much for adding it <3
Yeah the batch file will now do all of the work for me, updating No-Bling and Dota2Patcher.exe and then launching Dota 2

Dota2Patcher.exe -s -1 works flawlessly:)
