### ISSUE TITLE
Another question!

### ISSUE THREAD

**Issue by Lgazana** [Wolf49406/Dota2Patcher#3]
Hi, @Wolf49406

Thank you for the update! the patcher is excellent, and I appreciate the new revert feature. I only have two questions.

1. I'm just curious what 'Patch sv_cheats' actually does. I'm asking because it wasn't required in version 2.3.1, so why is it required now in version 3.0.0? Is it because it's more secure or something?

2. Also, are there any other console commands you'd recommend in addition to these, or is there none? :P

sv_cheats1; dota_use_particle_fow 0; fog_enable 0; fow_client_nofiltering 1; dota_camera_distance 1500; r_farz 3000; dota_range_display 0; cl_weather 8;

**Comment by Wolf49406** [comment]
The old way didn't let you set sv_cheats to 1.
In 2.3.x, ConVars like "dota_camera_distance" simply didn't need sv_cheats at all.
But for some reason "dota_range_display" (and probably some other commands) didn't work, so you have to set sv_cheats to 1.
And the old way didn't let you to do this. So I had to find a different way of patching.

**Comment by Lgazana** [comment]
I see what you're saying.
Okay, thank you for responding and explaining everything again!
