### ISSUE TITLE
dota+

### ISSUE THREAD

**Issue by Scrymen** [Wolf49406/Dota2Patcher#35]
I can't quite figure out what exactly I need to do in order to patch only dota+. After downloading and opening Dota2Patcher.exe it tells me that "Dota Plus Unlocked" but this does not happen when I enter dota itself. What have I done wrong?

**Comment by Lexorily** [comment]
Returned to being Broken

**Comment by Scrymen** [comment]
> Returned to being Broken

Do you have same problem ?

**Comment by sonhador93** [comment]
dota plus not work

**Comment by Wolf49406** [comment]
No shit Sherlock.
