### ISSUE TITLE
question ..

### ISSUE THREAD

**Issue by VP123445** [Wolf49406/Dota2Patcher#4]
I dont understand this step 

Drop desired vpk to your mods folder inside \dota 2 beta\game\ (ex: \dota 2 beta\game\dota_tempcontent);

What i have done:
1. Download latest Dota2Patcher release;
2. Launch it, select [1] Patch All 
3. Open \dota 2 beta\game\dota\gameinfo.gi with text editor;
4. Change line 39 to Game dota_tempcontent
5. And line 40 to Mod dota_tempcontent

**Comment by Wolf49406** [comment]
Well just move your mods file (VPK) to  \dota 2 beta\game\dota_tempcontent.
If you need NoBling, just launch it, it will move vpk there.

**Comment by VP123445** [comment]
Помоему ты русскоязычный, короче вообще не работает)) Пропатчил, в гейминфо все прописано, ноублинг запустил, оно там все сделало как раньше работало, темпконтент прописан, вообще не помогает, все анимации имморталок и шмотки сверкают и свистопердят, а мне бы отрубить.../:ccc

**Comment by Wolf49406** [comment]
Покажи, как у тебя gameinfo.gi выглядит. И в какой папке vpk лежат. 
-tempcontent больше не работает, кстати, эту опцию вообще удалили из доты.

**Comment by VP123445** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/49289570/151628844-bf7bf2d8-1b7a-4d9f-b472-6497ddbf43cc.png)
![Screenshot_6](https://user-images.githubusercontent.com/49289570/151628846-bf0c9c4b-efdd-4555-9144-f9bc95f0b217.png)

Вот так все лежит, заранее благодарен)

**Comment by Wolf49406** [comment]
А, ну понятно. Зря я везде рассказал об этом патче -- пофиксили #5 :D 
Ладно, буду смотреть, что там изменили.

**Comment by Wolf49406** [comment]
Обновил, перекачай новый релиз.
