### ISSUE TITLE
Gameinfo Bypass Offset is NULL!

### ISSUE THREAD

**Issue by metita** [Wolf49406/Dota2Patcher#42]
Title.

**Comment by Wolf49406** [comment]
idk man. Revert and patch it again. I guess, it's just already patched.
![image](https://user-images.githubusercontent.com/26302888/196013968-eb6a41d3-9180-43dd-939d-1a82457ae504.png)

**Comment by metita** [comment]
Looks like a pretty rare bug that DotA won't allow you to play due to VAC (modified files) and when trying to Patch Gameinfo an error is thrown but yeah, need to Revert patches and it works like a charm.
