### ISSUE TITLE
After Diretide 2022 update: VAC matchmaking disabled after re-modifying gameinfo.gi and patching Gameinfo

### ISSUE THREAD

**Issue by gnatdagnat** [Wolf49406/Dota2Patcher#46]
I'm using it for no-bling. After the latest Dota 2 client patch my gameinfo.gi was reset, I edited it again. Then used Patcher. Now my matchmaking has VAC warning. Any insight? Patcher needing update? @Wolf49406 or others

**Comment by sonhador93** [comment]
+ update patcher pls

**Comment by tophlock** [comment]
you need to use the patcher everytime there is an update

**Comment by gnatdagnat** [comment]
> you need to use the patcher everytime there is an update

Indeed, as I have done. I said so in the post.

**Comment by gnatdagnat** [comment]
It's inexplicably resolved for me. You guys can open new issue if there's a real problem but I guess there's not.

**Comment by MaimedThoughts** [comment]
> It's inexplicably resolved for me.

How? 0.o
I'm still getting the same warning "Locally modified game files detected. Play is disabled." So the patcher requires an update. There is no magical way to fix it without it.

**Comment by gnatdagnat** [comment]
> 

I don't honestly know. there was a 45MB or so Dota patch and I re-patched gameinfo and it just went away 🤷

**Comment by robbyz512** [comment]
@MaimedThoughts you have to patch twice for some reason, open dota2patcher patch gameinfo, then repeat again.

no idea why it only works that way right now credits to @XkTheMaster

**Comment by MaimedThoughts** [comment]
lmao yeah, that worked, thank you @robbyz512 !!
