### ISSUE TITLE
[-] Gameinfo Bypass Offset is NULL!  v3.0.5.7

### ISSUE THREAD

**Issue by beingrus** [Wolf49406/Dota2Patcher#47]
[-] Gameinfo Bypass Offset is NULL after updating

**Comment by imoonkin** [comment]
> 0x80, 0x7F, 0x39, 0x00, 0x74

change 74 to EB, you can check author's new commit for a clue

**Comment by Wolf49406** [comment]
Yep, my bad.
[cf784e9](https://github.com/Wolf49406/Dota2Patcher/commit/cf784e9370001563e3267bf2fe953289ef75d675)
