### ISSUE TITLE
today's update caused a problem

### ISSUE THREAD

**Issue by Lgazana** [Wolf49406/Dota2Patcher#5]
The patcher appears to be unable to patch the 'GameInfo' as of today's update. I also looked in HxD for the numbers '44 38 67 39 74 39', but I can't find them. I'm guessing they changed or something. Is this a permanent fix from Valve, or is there still a workaround?
![2022-01-29 02_21_10-D__My Programs_CHEATS_Dota2_Dota2Patcher_v3 0 1 exe](https://user-images.githubusercontent.com/50317210/151642210-2ef69145-d9f3-4214-96a0-0ef605cf5e15.png)
![2022-01-29 02_17_02-Information](https://user-images.githubusercontent.com/50317210/151642213-8134a88f-9dcf-4862-ae78-a387b4d7ae02.png)

**Comment by Wolf49406** [comment]
Yup, Valve fixed that. It was expected. Guess I'll have to find a new way.

**Comment by Lgazana** [comment]
That's really sadge. Best wishes, and I hope you find a new way soon because I can't take it here anymore playing with 30 fps xD.

**Comment by DiskordK** [comment]
Is Valve doing this intentionally? They literally don't touch scripts, at same time, from  moment of prohibition -tempcontent, Valve has been releasing ~5 micro updates that break nobling and so on.

**Comment by Wolf49406** [comment]
Nah, don't think they did it intentionally. I hope it's just broken patter. It wasn't perfect.
I need to open client.dll in IDA, it takes a lot of time bc of my potato PC.

**Comment by Wolf49406** [comment]
![image](https://user-images.githubusercontent.com/26302888/151659425-0bf3870e-c53c-4065-be37-19d9ed6b901b.png)

**Comment by Wolf49406** [comment]
Fixed in 5542e55, download a new release.
