### ISSUE TITLE
Not working pubs

### ISSUE THREAD

**Issue by elventevil** [Wolf49406/Dota2Patcher#6]
its only working demo mode when try to use in real game not working

[Console] SV: Convar 'dota_use_particle_fow' is cheat protected, change ignored.
[Console] SV: Convar 'fog_enable' is cheat protected, change ignored.
[Console] SV: Convar 'fow_client_nofiltering' is cheat protected, change ignored.
[Console] SV: Convar 'dota_camera_distance' is cheat protected, change ignored.
[Console] SV: Convar 'r_farz' is cheat protected, change ignored.

**Comment by DiskordK** [comment]
Не хочется создавать отдельный тред, спрошу здесь. @Wolf49406 
Всегда ли так работало?
Использую только патчинг gameinfo для ноблинга, и если раньше при новых апдейтах отваливался весь поиск, то сегодня обнаружил, что обычный поиск работает, а при попытке найти рейтинг выдает сообщение об изменении локальных файлов.

**Comment by Wolf49406** [comment]
> [Console] SV: Convar 'dota_use_particle_fow' is cheat protected, change ignored.
> [Console] SV: Convar 'fog_enable' is cheat protected, change ignored.
> [Console] SV: Convar 'fow_client_nofiltering' is cheat protected, change ignored.
> [Console] SV: Convar 'dota_camera_distance' is cheat protected, change ignored.
> [Console] SV: Convar 'r_farz' is cheat protected, change ignored.
![image](https://user-images.githubusercontent.com/26302888/152083414-822010a3-c334-41e2-954d-a5004b55e010.png)

**Comment by Wolf49406** [comment]
> Не хочется создавать отдельный тред, спрошу здесь. @Wolf49406 Всегда ли так работало? Использую только патчинг gameinfo для ноблинга, и если раньше при новых апдейтах отваливался весь поиск, то сегодня обнаружил, что обычный поиск работает, а при попытке найти рейтинг выдает сообщение об изменении локальных файлов.

Да, подтверждаю, опять что-то изменили. Позже буду смотреть, в чем дело.

**Comment by Wolf49406** [comment]
f4e94f3
