### ISSUE TITLE
warnign from valvle for using it on 2/2/22 

### ISSUE THREAD

**Issue by fuffyk** [Wolf49406/Dota2Patcher#9]
Got warning to fix error by validating game files and restartign compuyter. is it being detected as not allowed now? thanks

**Comment by Wolf49406** [comment]
Idk everything's ok for me. Try to patch again mb?
![image](https://user-images.githubusercontent.com/26302888/155291113-b222c55d-ecb0-4a3e-be02-e79296f9d84a.png)

**Comment by metapodcod** [comment]
> Idk everything's ok for me. Try to patch again mb? Also it looks like your vpk-mods outdated. ![image](https://user-images.githubusercontent.com/26302888/155336119-dca1e20d-d562-4a2d-8be8-db8c8a98e289.png)

Where can we download vpk mods, any suggestions?

**Comment by Wolf49406** [comment]
Just build some yourself.
* Install Workshop Tools DLC; 
* Download [VRF](https://vrf.steamdb.info/); 
* Google how to compile vpk;
* Open `\dota 2 beta\game\dota\pak01_001.vpk` with VRF;
* Get files you need;
* Build your vpk;

**Comment by metapodcod** [comment]
> @metapodcod Just build some yourself.
> 
> * Download [VRF](https://vrf.steamdb.info/);
> * Google how to compile vpk;
> * Open `\dota 2 beta\game\dota\pak01_001.vpk` with VRF;
> * Get files you need;
> * Build your vpk;

I asked about the mods you used, thank you for this information. I'm looking for something like this to increase FPS https://github.com/No-Bling/DOTA/issues/73#issuecomment-853855669  Some things are explained here, but I couldn't understand anything because there is no video tutorial. https://github.com/No-Bling/DOTA/issues/47

**Comment by Wolf49406** [comment]
I use only this mod to fix main menu.
[pak01_dir.zip](https://github.com/Wolf49406/Dota2Patcher/files/8140055/pak01_dir.zip)
![image](https://user-images.githubusercontent.com/26302888/155690012-75dda994-5fd5-4664-acfb-5bed0a0cee6a.png)
